:cop: fix github actions spacing/format

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -25,6 +25,6 @@ jobs:
       env:
         CI: true
     - name: run Lighthouse CI
-        run: |
-          npm install -g @lhci/cli@0.3.x
-          lhci autorun --upload.target=temporary-public-storage --staticDistDir=./built || echo "LHCI failed!"
+      run: |
+        npm install -g @lhci/cli@0.3.x
+        lhci autorun --upload.target=temporary-public-storage --staticDistDir=./built || echo "LHCI failed!"
